name: Mi Primera Prueba

on:
  schedule:
    # 30 = minuto, 20 = hora en UTC (que son las 22:30 en España)
    - cron: '30 20 * * *'
  
  workflow_dispatch:

jobs:
  testear-codigo:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Obtener mi código
        uses: actions/checkout@v4

      - name: 2. Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Ejecutar mi prueba
        # Fíjate que aquí no hay paso de 'pip install', 
        # pasamos directo a ejecutar el código.
        run: python prueba.py
